[package]
name = "pbrt-rs"
version = "0.1.0"
authors = ["Tomasz Cichocinski <tomaszcichocinski@gmail.com>"]

[dependencies]
image = "0.19.0"
serde = "1.0.70"
rand = "0.6.5"
rayon = "1.1"

[profile.release]
debug = true
